name: NPM Publish  
  
on:  
  push:  
    tags:  
      - 'v*' # 触发条件，这里设置为当推送包含v前缀的标签时  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v3  
      - uses: actions/setup-node@v3  
        with:  
          node-version: '16' # 使用Node.js 16，你可以根据需要更改  
          registry-url: 'https://registry.npmjs.org/' # npm仓库URL  
      - run: npm ci  
      - run: npm test # 如果你的项目有测试，请取消注释这行  
      - run: npm publish  
        env:  
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # 使用之前创建的npm访问令牌
