name: NPM Publish  
  
on:  
  push:  
    tags:  
      - 'v*' # 当推送包含v前缀的标签时触发  
  
jobs:  
  build-and-publish:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v3 # 使用最新版本的actions/checkout  
      - uses: actions/cache@v3 # 使用最新版本的actions/cache来缓存node_modules  
        with:  
          path: |  
            **/node_modules  
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  
          restore-keys: |  
            ${{ runner.os }}-node-  
      - uses: actions/setup-node@v3 # 使用最新版本的actions/setup-node  
        with:  
          node-version: '20.x' # 设置Node.js版本为20.x  
          registry-url: 'https://registry.npmjs.org/' # 可选，但通常不需要显式设置，除非你有特殊的npm仓库  
      - run: npm ci  
      - run: npm test # 如果你的项目有测试，请取消注释这行  
      - run: npm publish  
        env:  
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # 使用存储在GitHub Secrets中的NPM令牌
